language: csharp
mono: none
dotnet: 2.0.0

install:
- dotnet restore

before_script:
- npm i -g npm

script:
- dotnet publish > /dev/null
        # - dotnet build
#  - dotnet test MTAServiceStatus.Tests/MTAServiceStatus.Tests.csproj
